/*
 * Menshen API
 * This is a LEAP VPN Service API
 *
 * OpenAPI spec version: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ModelsLocation;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ModelsEIPService
 */

public class ModelsEIPService {
  @SerializedName("auth")
  private String auth = null;

  @SerializedName("locations")
  private Map<String, ModelsLocation> locations = null;

  @SerializedName("openvpn_configuration")
  private Map<String, Object> openvpnConfiguration = null;

  @SerializedName("serial")
  private Integer serial = null;

  @SerializedName("version")
  private Integer version = null;

  public ModelsEIPService auth(String auth) {
    this.auth = auth;
    return this;
  }

   /**
   * Get auth
   * @return auth
  **/
  @ApiModelProperty(value = "")
  public String getAuth() {
    return auth;
  }

  public void setAuth(String auth) {
    this.auth = auth;
  }

  public ModelsEIPService locations(Map<String, ModelsLocation> locations) {
    this.locations = locations;
    return this;
  }

  public ModelsEIPService putLocationsItem(String key, ModelsLocation locationsItem) {
    if (this.locations == null) {
      this.locations = new HashMap<String, ModelsLocation>();
    }
    this.locations.put(key, locationsItem);
    return this;
  }

   /**
   * Get locations
   * @return locations
  **/
  @ApiModelProperty(value = "")
  public Map<String, ModelsLocation> getLocations() {
    return locations;
  }

  public void setLocations(Map<String, ModelsLocation> locations) {
    this.locations = locations;
  }

  public ModelsEIPService openvpnConfiguration(Map<String, Object> openvpnConfiguration) {
    this.openvpnConfiguration = openvpnConfiguration;
    return this;
  }

  public ModelsEIPService putOpenvpnConfigurationItem(String key, Object openvpnConfigurationItem) {
    if (this.openvpnConfiguration == null) {
      this.openvpnConfiguration = new HashMap<String, Object>();
    }
    this.openvpnConfiguration.put(key, openvpnConfigurationItem);
    return this;
  }

   /**
   * Get openvpnConfiguration
   * @return openvpnConfiguration
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getOpenvpnConfiguration() {
    return openvpnConfiguration;
  }

  public void setOpenvpnConfiguration(Map<String, Object> openvpnConfiguration) {
    this.openvpnConfiguration = openvpnConfiguration;
  }

  public ModelsEIPService serial(Integer serial) {
    this.serial = serial;
    return this;
  }

   /**
   * Get serial
   * @return serial
  **/
  @ApiModelProperty(value = "")
  public Integer getSerial() {
    return serial;
  }

  public void setSerial(Integer serial) {
    this.serial = serial;
  }

  public ModelsEIPService version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsEIPService modelsEIPService = (ModelsEIPService) o;
    return Objects.equals(this.auth, modelsEIPService.auth) &&
        Objects.equals(this.locations, modelsEIPService.locations) &&
        Objects.equals(this.openvpnConfiguration, modelsEIPService.openvpnConfiguration) &&
        Objects.equals(this.serial, modelsEIPService.serial) &&
        Objects.equals(this.version, modelsEIPService.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(auth, locations, openvpnConfiguration, serial, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsEIPService {\n");
    
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    openvpnConfiguration: ").append(toIndentedString(openvpnConfiguration)).append("\n");
    sb.append("    serial: ").append(toIndentedString(serial)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

