/*
 * Menshen API
 * This is a LEAP VPN Service API
 *
 * OpenAPI spec version: 0.5.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Operational properties which describe how the provider offers the service
 */
@ApiModel(description = "Operational properties which describe how the provider offers the service")

public class ModelsProviderService {
  @SerializedName("allow_anonymous")
  private Boolean allowAnonymous = null;

  @SerializedName("allow_registration")
  private Boolean allowRegistration = null;

  public ModelsProviderService allowAnonymous(Boolean allowAnonymous) {
    this.allowAnonymous = allowAnonymous;
    return this;
  }

   /**
   * Flag indicating if anonymous usage without registration is allowed deprecated: kept for backwards compatibility
   * @return allowAnonymous
  **/
  @ApiModelProperty(value = "Flag indicating if anonymous usage without registration is allowed deprecated: kept for backwards compatibility")
  public Boolean isAllowAnonymous() {
    return allowAnonymous;
  }

  public void setAllowAnonymous(Boolean allowAnonymous) {
    this.allowAnonymous = allowAnonymous;
  }

  public ModelsProviderService allowRegistration(Boolean allowRegistration) {
    this.allowRegistration = allowRegistration;
    return this;
  }

   /**
   * Flag indicating if the provider supports user registration deprecated: kept for backwards compatibility
   * @return allowRegistration
  **/
  @ApiModelProperty(value = "Flag indicating if the provider supports user registration deprecated: kept for backwards compatibility")
  public Boolean isAllowRegistration() {
    return allowRegistration;
  }

  public void setAllowRegistration(Boolean allowRegistration) {
    this.allowRegistration = allowRegistration;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsProviderService modelsProviderService = (ModelsProviderService) o;
    return Objects.equals(this.allowAnonymous, modelsProviderService.allowAnonymous) &&
        Objects.equals(this.allowRegistration, modelsProviderService.allowRegistration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowAnonymous, allowRegistration);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsProviderService {\n");
    
    sb.append("    allowAnonymous: ").append(toIndentedString(allowAnonymous)).append("\n");
    sb.append("    allowRegistration: ").append(toIndentedString(allowRegistration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

