# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

   desc "Build debug and test APK for screenshots"
   lane :build_bitmask_for_screengrab do
      gradle(
        task: 'clean'
      )
      gradle(
        task: 'assemble',
        build_type: 'Debug',
        flavor: 'NormalProductionFat'
      )
      gradle(
        task: 'assemble',
        build_type: 'DebugAndroidTest',
        flavor: 'NormalProductionFat'
      )
  end

     desc "Build debug and test APK for screenshots"
     lane :build_custom_for_screengrab do
        gradle(
          task: 'clean'
        )
        gradle(
          task: 'assemble',
          build_type: 'Debug',
          flavor: 'CustomProductionFat'
        )
        gradle(
          task: 'assemble',
          build_type: 'DebugAndroidTest',
          flavor: 'CustomProductionFat'
        )
    end

  lane :bitmask_screenshots do
    # Prepare builds for Automatic UI Tests
    build_bitmask_for_screengrab
    capture_android_screenshots
    frameit(white: true)
    # deliver
  end

   lane :custom_build_screenshots do
     # Prepare builds for Automatic UI Tests
     build_custom_for_screengrab
     capture_android_screenshots
     frameit(white: true)
     # deliver
   end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
